# Generated by Django 4.0.4 on 2022-05-27 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6)),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('age', models.IntegerField()),
                ('lifestyle', models.CharField(choices=[('1.2', 'Sedentary'), ('1.375', 'Lightly active'), ('1.55', 'Moderately active'), ('1.725', 'Very active'), ('1.9', 'Extra active')], max_length=20)),
            ],
        ),
    ]
