# Generated by Django 4.0.4 on 2022-05-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calories_Calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=50)),
                ('food_calories', models.IntegerField()),
            ],
        ),
    ]
