# Generated by Django 4.0.4 on 2022-05-27 12:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Calories_Calculator', '0002_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='food_time',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meal',
            name='food_name',
            field=models.CharField(max_length=50),
        ),
    ]
